### ISSUE TITLE
Type.Namespace and FullName outputting incorrectly by LeMP

### ISSUE THREAD

**Issue by dadhi** [qwertie/ecsharp#116]
I have this code inside `quote {}`

```cs
precompute(factories.Select((f, i) => quote {
    if (serviceType == typeof($(LNode.Id(typeof(A).FullName))))
```

and expecting
```cs
    if (serviceType == typeof(LibWithEcs.A)) {
```

but getting
```cs
   if (serviceType == typeof(Submission_num1_plusA)) {
```

Btw, if I output `Namespace` along I am getting `@__empty__ ` instead.

The `A` is defined in `compileAndRuntime` earlier in the same file:

```cs
    namespace LibWithEcs
    {
        public class A {}

```

Here is the commit: https://github.com/dadhi/LempTest/commit/2956c1a114c9b63b247a7bd72efec3129dd968b3

So, for now, I am omitting the namespace in the output.

**Comment by dadhi** [comment]
Ok, seems like A namespace is just empty, so it is stripped for some reason.

**Comment by qwertie** [comment]
Consider this C# interactive session:

    > class A { public class InnerA { } }
    > typeof (A.InnerA).FullName
    "Submission#21+A+InnerA"

When sanitized into a valid identifier, this is `Submission_num21_plusA_plusInnerA`. Since `compileTime` is based on the C# Interactive engine, this explains the result you're getting. Remember that namespaces are not supported by C# interactive and are stripped out by LeMP.

Even if namespaces were supported, `LNode.Id(typeof(A).FullName)` still wouldn't do what you want, because `Namespace.A` is not an identifier, it is an expression that calls the `.` operator. If you treat `Namespace.A` as an identifier, it will be sanitized into `Namespace_periodA` in the output. Instead, you would need to write a function to convert the string "Namespace.A" into an expression.

**Comment by dadhi** [comment]
Ok, thanks for the answer.
