### ISSUE TITLE
Creating a parser for expression trees

### ISSUE THREAD

**Issue by glopesdev** [qwertie/ecsharp#18]
I just very recently learned about LLLPG. I think it is really great work and inspired me to try and tackle a challenge that I find simply incredible that noone has ever tackled comprehensively before: **a parser for expression trees**.

**What is the goal?**
Expression trees are presumably capable of representing every single C# expression, including LINQ, lambdas, anonymous type declarations, etc. The goal is to have a parser that can take any C# expression and produce the equivalent expression tree.

**Why expression trees?**
I believe expression trees are hands-down the most powerful and balanced runtime code generation tool across the C# stack today. They:
- work in virtually every platform because of LINQ-query compatibility;
- have excellent debugger support;
- can generate fast and garbage-collectible code;
- provide multiple extensibility points for mixing an expression tree with an existing host environment

At first look they are the PERFECT candidate for lightweight C# scripting, except for one huge catch: apart from the built-in C# parser support to generate `Expression<TLambda>` instances, there is no equally _lightweight_ support for parsing Expression trees from text.

**Why not use Roslyn?**
Roslyn is an absolutely amazing piece of software; a death star to detonate the entire constellation of .NET code generation problems. This is also it's greatest weakness, because by necessity it is not lightweight at all. Taking a dependency on Roslyn is a huge commitment and effectively eliminates many of the platforms and scenarios where you might want to deploy this (such as mobile).

**Are you sure noone tried to do this before?**
Actually, they have. The best attempt so far is [ExpressionEvaluator](https://csharpeval.codeplex.com/). ExpressionEvaluator fulfills the requirement of being relatively lightweight (except for the Antlr runtime). However, they have no support for LINQ or lambdas yet, which in my opinion are the most interesting uses of scripting C# expressions (for manipulating collections, etc). In studying their source code I realized that there is much I need to relearn about parsers (it's been a while since I last wrote parsers and lexers - for university projects) and eventually got to the point where I am essentially starting from scratch again (grammar files).

It was at this point that I learned about LLLPG. I realized it raised the serious possibility of generating parsers with no extra runtime dependencies (e.g. without Antlr) which is a huge bonus, and it looks self-contained and lightweight enough that I could actually start relearning parser writing. Making this parser a reality would be the best learning exercise.

**My question is:** has any of you guys ever thought/tried to do this? Am I crazy in thinking that this would be insanely useful and a great contribution to industry/independent developers? I post this issue thinking that it is in line with the spirit of Loyc. I have gone through the ECS grammar, parser and lexer and am thinking of adapting it to the purposes of this exercise, but would have to extend it (eventually) to handle LINQ and so on.

I would love to get some feedback/suggestions/comments before I get started, especially if there is any particular deadend that you imagine I may be getting myself into. I have a reasonable time to learn at this moment, so if there is any time to do this, now is the time.

Thanks for developing this amazing tool and hope that somehow this is the start of seeing the dream of a C# Expression Tree parser come true!

**Comment by qwertie** [comment]
Well, me, I haven't ever had a direct use for expression trees. I don't even remember how they deal with typing information (is it... optionally typed?). I probably used them in Linq-to-SQL, but that's it, since I find parsing of "any executable code block" or "any code block" to be a much more useful concept. So I am curious, if you had a expression-only parser, what would you use it for?

It would be really appreciated if you could figure out how to parse LINQ expressions into `LNode`s first by modifying the existing `Ecs/Parser/EcsParserGrammar.les` in this repo... but if you prefer to go the other route and directly produce expression trees from all expessions (including LINQ), I'd be curious to see the results. Back when I looked into parsing LINQ expressions, I had difficulty finding complete information about the various types of LINQ expressions and how they are translated into C#-without-lambda-expressions. Technically, that information can be found in the [C# language reference](https://www.microsoft.com/en-us/download/details.aspx?id=7029), but it is not easy reading.

If you want to rip out the EC# expression parser and turn it into a plain-C# expression parser, you'd want to remove the EC#-specific things. The following comes to mind:

- EC# allows braced blocks in expressions, like `2 + {bool c = x*y; if (c > 0) x else y}`
- EC# allows tuples like `(x, y)`
- EC# allows variable declarations in expressions, like `(var Foo2 = Foo*Foo) * Foo2`

Making it more complicated to remove the latter two features is the fact that there is no special rule for lambda expressions; lambda is treated like any other infix operator! Thus `5 => 3+2` is valid, and `(x, y) => z` has a tuple on the LHS. So... it would be easier to write a converter from `LNode` to expression trees, but then your code will have more dependencies than you probably wanted.

Just a reminder: if you add Ecs.exe and its dependencies like Loyc.Syntax.dll as references to your project, you can parse a specified expression by calling 

    LNode expr = Ecs.Parser.EcsLanguageService.Value.ParseSingle(
        "your_expression(here)", null, ParsingService.Exprs);

To avoid creating intermediate `LNodes`, I think you could make new derived classes of `System.Linq.Expressions.Expression` to represent tuples and variable declarations, and then postprocess the output of the parser from `(A a, B b) => expr` (where the left-hand side is a tuple) into an `Expression<A, B>`. (Btw I'm a little confused: when I look at the documentation of [`Expression`](https://msdn.microsoft.com/en-us/library/system.linq.expressions.expression.aspx) it doesn't seem to have type parameters, and I don't see any links to the version of `Expression` that does have type parameters.)

**Comment by qwertie** [comment]
P.S. Thanks for your interest in LLLPG/Loyc, and let me know if I forgot to respond to anything!

**Comment by qwertie** [comment]
@glopesdev it appears based on [this question](http://stackoverflow.com/questions/821365/how-to-convert-a-string-to-its-equivalent-expression-tree) that you can already parse a string into an expression tree at run-time.

However, it would be straightforward to do it in Enhanced C# using `matchCode` - have a look at [this example](http://loyc.net/lemp/ref-other.html#matchcode) and imagine replacing the "Eval" function with a "CreateExpressionTree" function.
