### ISSUE TITLE
LES: consider making `!!` a prefix/suffix operator like `++/--`

### ISSUE THREAD

**Issue by qwertie** [qwertie/ecsharp#47]
Kotlin's [`!!` suffix operator](https://kotlinlang.org/docs/reference/null-safety.html) means "throw NullPointerException if the value to the left is null". Arguably LES should define it the same way. But we'd have to think about how we handle `!!.` as in `obj!!.field`.

**Comment by jonathanvdc** [comment]
Oh, that's pretty interesting. Do you also want to integrate `!!`/`!!.` into EC#? If so, in what way would `obj!!.field` differ from `obj.field`?

**Comment by qwertie** [comment]
It probably doesn't make sense in EC# - in Kotlin there are separate data types `Object` and `Object?` so `!!` is needed to convert the latter into the former. EC# is not likely to add non-null types except to copy whatever C# does. I also consider LES as having higher priority since I need to make a bunch of decisions before porting the LES parser to other languages. I would welcome your input on the questions mentioned [here](http://loyc.net/2017/lesv3-update.html#undecided-issues)... as well as the [minus sign issue](http://loyc.net/2017/negation-blues.html).

**Comment by jonathanvdc** [comment]
Your post about parsing negative numbers was an interesting read.

I think keeping LES as simple as possible is probably the best strategy. Always using string notation for negative numbers (i.e., `number"-1"` or `i"-1"`, as you suggested in your post) seems like a solid strategy. My reasoning is this:

 * People who want to use LES as a DSL (like you did in your graphing calculator) will probably end up implementing unary minus anyway, so they won't care whether LES parses `-1` as `@-(1)` or as a `-1` literal.
 * People who want to use LES as a data storage format (this is actually pretty much what Flame IR uses LES for) won't care much either because their files will typically be computer-generated. They'll probably spend *way more* time reading LES files than writing them, and `i"-1"` is readable enough.

I'm not saying that parsing `-1` as a literal has no valid use cases (manually writing a Flame IR file, for example, is one). But they really don't justify a complex implementation with funny edge cases in my opinion.

**Comment by Starwer** [comment]
Apparently, C# 8.0 will revolutionize the null-type by making all types value-types by default, unless declared otherwise using the `?` postfix like in `bool? myFlag;`
They will also implement a `!` meaning "I know this type is not null ! (throw exception at runtime otherwise)":
`if (!string.IsNullOrEmpty(obj))  length = obj!.Length; `

So I think this makes the proposed `!!` quite pointless.

BTW, even though I am not a user of this library, I'm positively impressed about the work done here.

**Comment by qwertie** [comment]
Hi Sebastien. Your comment would make sense in relation to Enhanced C#, but this is a thread about LES, which is conceptually unrelated to .NET. See http://loyc.net/les

**Comment by Starwer** [comment]
Indeed! My apologies ! I mixed up the two projects. Thanks for pointing out.

**Comment by qwertie** [comment]
`!!` and `!.` were actually added 2017-08-29 and I forgot to close the issue.
