### ISSUE TITLE
Comments not emitted based on surrounding whitespace

### ISSUE THREAD

**Issue by j4m3z0r** [qwertie/ecsharp#59]
While researching the test-cases in #58, I discovered that newlines surrounding comments can affect whether or not the comments are emitted in the output. For example:

```
#ecs;

namespace Test
{
	internal class Class
	{
		// #region test region
		
		[DllImport(Constants.Lib, EntryPoint = "testfunction")]
		public static extern int TestFunction(int i);
		//#endregion
	}
}
```

Will omit the first comment, whereas the comment is preserved in either of the following two versions:

```
#ecs;

namespace Test
{
	internal class Class
	{
		// #region test region
		[DllImport(Constants.Lib, EntryPoint = "testfunction")]
		public static extern int TestFunction(int i);
		//#endregion
	}
}
```

```
#ecs;

namespace Test
{
	internal class Class
	{

		// #region test region

		[DllImport(Constants.Lib, EntryPoint = "testfunction")]
		public static extern int TestFunction(int i);
		//#endregion
	}
}
```

**Comment by qwertie** [comment]
This will be fixed in the 2.9.0 release. The bug was in `#useSymbols` which is part of `#ecs`. The problem was that it would always recreate the braced block of a class, struct, or interface. So a comment, newline or `#region` would disappear if it was attached to the opening brace (`body.Target`) of a class, struct or interface.
