### ISSUE TITLE
Add mechanism to mark unused variables as ok

### ISSUE THREAD

**Issue by j4m3z0r** [qwertie/ecsharp#64]
Consider the following:
```
replace(BufferAndNativeTypes => (
    (Int, int),
    (Float, float),
    (Short, short),
    (UShort, ushort),
    (Byte, byte)));

            unroll((BufferType, NativeType) in BufferAndNativeTypes) {
                if(typeof(T) == typeof(NativeType)) {
                    return;
                }
            }
```
It will generate a warning, because `NativeType` isn't used.

Generally when I iterate over `BufferAndNativeTypes` I use both entries in the tuple, but here I don't. I generally like to eliminate all warnings where possible, so that it's meaningful when I do get one. I'd love to have a way to mark to LeMP that NativeType being unused is expected, so it doesn't need to generate a warning.

At present I'm doing this:
```
                #rawText("// "); #rawText(stringify(BufferType));
```
which works, but it's a bit of a hack.

**Comment by qwertie** [comment]
If you use `(_, NativeType)` the warning will go away. (If that didn't work I was going to suggest adding `[#trivia_unused(BufferType)]` which would suppress it without producing output, as any unrecognized trivia will be ignored by the printer; this latter fix would not have been ideal since the definition of trivia [will change](https://github.com/qwertie/ecsharp/issues/61)).
