### ISSUE TITLE
http://ecsharp.net/ecs/for-pl-nerds-part-4.html looks jumbled

### ISSUE THREAD

**Issue by EmmanuelOga** [qwertie/ecsharp#67]
Hi,

I was browsing the docs and noticed [this page](http://ecsharp.net/ecs/for-pl-nerds-part-4.html ) looks jumbled. I located this markdown page:

https://github.com/qwertie/ecsharp/blob/gh-pages/ecs/for-pl-nerds-part-4.md

...which seems to render nicely, so maybe there was some hiccup while converting the page to html?

Greets!

**Comment by qwertie** [comment]
Okay, I have fixed the garbledness - the problem was that the article was unfinished (still is) and contained something that resembled an HTML tag, which turned off the Markdown parser. Sorry for taking so long!

I don't know whether to be happy that somebody potentially read all the way to part four, or horrified that you read about a bunch of old ideas that I'll probably never get around to doing (some of which I know Microsoft will be doing, or I know MS will so something related). What do you think?

**Comment by EmmanuelOga** [comment]
Hey David,

I arrived to your sites twice: once when I was first starting with C#. I thought, "C# is a great language, if only there was a way to write macros to avoid the ceremony about getters/setters/INotifyPropertyChanged/etc..), then I found ecsharp, although, sadly, I did not try it yet, but this is a failure of mine not the project! The second time around I spend more time reading the site docs, that's how I found the broken page. Honestly, going through your docs is a bit daunting at times because it feels there's so much there to read (yes, this is just me being lazy... sorry!) :-) 

The second time around was because I had this idea about documenting interfaces, and the best kind of documentation is machine readable specs IMO... long story short I thought it would be cool to have some sort of IDL to describe algorithms at a very high level a have a single AST that could be used to generate code for several different programming languages. I think googled something akind to "universal abstract syntax tree", that's when I found the Loyc trees article!

At that point I had stumbled upon your site twice, on two different searches, so I thought it was gonna be a good idea to browse the rest of your  production. I enjoyed reading a lot of your blog posts! It is great that you share so much detail not only about the technical side but about the emotional side of personal projects. Since programming is not only science, it is also art, it makes sense that it evokes emotion. But I'm starting to ramble :-p

I need to do more reading about loyc, and I'll probably try ecsharp too at some point. I've also been doing some clojure reading this days, and that stuff is so cool that confess I've left aside the dotnet platform for a bit these days.

If you are curious about it and you haven't come across it yet, take a look at https://clojure.org/about/spec. Since it seems like we share some ideas about how software development could be different / better, maybe you too will find clojure.spec interesting, :-)

Greets!

**Comment by EmmanuelOga** [comment]
Fixed!

**Comment by EmmanuelOga** [comment]
Note: related/this seems up your alley:

https://brianmckenna.org/blog/polymorphic_programming
https://isomorf.io/

**Comment by qwertie** [comment]
Oh, I forgot to thank you for telling your story. Thanks Emmanuel :D

I just looked at clojure.spec and found it incomprehensible. Maybe I would understand better if I had ever used Clojure...?

Isomorf reminds me of Jonathan Edwards ideas of a visual programming language and JetBrains' MPS system. It looks like you have to sign up for an account before you can try it, so I didn't bother. I didn't pay a lot of attention to these ideas in the past because I find it difficult to imagine programming with a tool that doesn't allow syntax errors - it implies I can't, in general, type out a statement since it will have syntax errors before the statement is complete - and it implies there is no usable text notation, so ordinary diff tools, like in my git front-end, won't work. I dunno, maybe I should have at least given MPS a try, it's the coolest non-text programming tool I've seen.
