### ISSUE TITLE
How can i use Lemp in my own compiler?

### ISSUE THREAD

**Issue by furesoft** [qwertie/ecsharp#89]

**Comment by qwertie** [comment]
It depends. Are you writing a compiler in .NET? Do you intend to write your own parser, or can you make a language based on LES?

**Comment by furesoft** [comment]
Im writing a compiler in .Net. I write my own Parser with custom Syntax

**Comment by qwertie** [comment]
In order to use LeMP, your parser needs to produce a Loyc tree for LeMP to process.

You should also write a class for macros you want to always be available in your language. You may want to write this class in Enhanced C# so that you can transform syntax trees easily:

~~~cs
#ecs;
using System;
using Loyc;
using Loyc.Syntax;
using Loyc.Collections;

namespace YourLanguage {
    [ContainsMacros]
    public static partial class Macros {
        // This is an example macro that transforms the "x...y" operator.
        [LexicalMacro("lo...hi", "Given `lo...hi, produces `Range.Inclusive(lo, hi)", "'...")]
        public static LNode RangeIncl(LNode node, IMacroContext context)
        {
            matchCode(node) {
                case $_($lo, $hi): // expect a call with two arguments
                    return quote(Range.Inclusive($lo, $hi));
                default:
                    return null;
            }
        }
    }
}
~~~

Then you'll create an instance of the macro processor that uses these macros:

~~~
var lmp = new LeMP.MacroProcessor(ConsoleMessageSink.Value, typeof(YourLanguage.Macros))
lmp.PreOpenedNamespaces.Add((Symbol) nameof(YourLanguage));
~~~

The simplest way to use LeMP is to call `ProcessSynchronously`:

~~~
var filename = "/path/source-file";
var stream = new FileStream(filename, FileMode.Open);
// replace this with your own parser
var code = Loyc.Syntax.Les.Les3LanguageService.Value.Parse(new StreamCharSource(stream), filename, ConsoleMessageSink.Value, ParsingMode.File, true);
VList<LNode> output = lmp.ProcessSynchronously(LNode.List(code));
~~~

If you want to be able to process all source files in parallel, LeMP requires you to write a class that implements `IParsingService` for your language. But you don't have to implement `Tokenize` or the `Parse` methods that deal with tokens. So, something like this:

~~~
public class YourParsingService : IParsingService
{
    public static YourParsingService Value = new YourParsingService();

    public IEnumerable<string> FileExtensions => new[] { "yourext" };
    public bool HasTokenizer => false;
    public bool CanPreserveComments => false;

    public IListSource<LNode> Parse(ICharSource text, string fileName, IMessageSink msgs = null, ParsingMode mode = null,
        bool preserveComments = true)
    {
        // Replace this with your parser
        return Syntax.Les.Les3LanguageService.Value.Parse(text, fileName, msgs, mode, preserveComments);
    }

    public IListSource<LNode> Parse(ILexer<Token> input, IMessageSink msgs = null, ParsingMode mode = null, bool preserveComments = true)
    {
        throw new NotImplementedException();
    }

    public IListSource<LNode> Parse(IListSource<Token> tokens, ISourceFile file, IMessageSink msgs, ParsingMode inputType)
    {
        throw new NotImplementedException();
    }
    public ILexer<Token> Tokenize(ICharSource text, string fileName, IMessageSink msgs)
    {
        throw new NotImplementedException();
    }
}
~~~

You can officially register the parsing service like this (optional):

~~~
ParsingService.Register(YourParsingService.Value);
~~~

Next, create an `InputOutput` object for each source file:

~~~
var fileList = new List<InputOutput>();
var filename = "/path/source-file";
var stream = new FileStream(filename, FileMode.Open);
fileList.Add(new LeMP.InputOutput(new StreamCharSource(stream), filename, YourParsingService.Value));
~~~

Then run the macro processor:

~~~
lmp.ProcessParallel(fileList, (InputOutput io) => {});
~~~

The lambda will be called after each file is done processing, and `io.Output` contains the output node list (`VList<LNode>`).

**Comment by qwertie** [comment]
All of this will work best if your Loyc trees resemble the ones produced by Enhanced C#. For example, the names of operators should start with a single quote (`` `'+`(x, y)`` meaning `x+y`), if-statements can be represented by `#if(condition, trueBranch, falseBranch)`, etc.

**Comment by furesoft** [comment]
ive startet the parser, it produces already an loyc tree. i think your tree is very good and flexible. 
is there a tutorial for writing a printer for my custom language?

**Comment by qwertie** [comment]
It has been on my to-do list for a long time to figure out how to write a printer more easily. Maybe I will have time to figure that out on Sunday and give you suggestions.

**Comment by furesoft** [comment]
that would be nice.

**Comment by qwertie** [comment]
Sorry, I didn't have time today. Hopefully later..
